# Generated by Django 4.2.6 on 2023-11-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_books_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='picture',
            new_name='pictures',
        ),
    ]
